/* eslint-disable react-refresh/only-export-components */
import { Navigate, Link } from 'react-router-dom';
import { ArrowLeft, Loader2, RefreshCw, X } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { ADMIN_EMAILS, isAdminEmail } from '@/lib/admin';
import { fRp } from '@/utils/format';

export function AdminGuard({ children }: { children: React.ReactNode }) {
  const { user } = useAuth();
  if (!user) return <Navigate to="/login" replace />;
  if (!isAdminEmail(user.email)) {
    return <div className="min-h-screen bg-slate-100 px-4 py-12"><div className="mx-auto max-w-xl rounded-3xl border border-red-200 bg-white p-8 text-center shadow-sm"><p className="text-sm font-black uppercase tracking-[0.2em] text-red-500">Akses Ditolak</p><h1 className="mt-3 text-2xl font-black text-slate-900">Halaman ini khusus admin.</h1><p className="mt-3 text-sm text-slate-500">Email kamu belum ada di whitelist admin.</p><p className="mt-4 text-xs text-slate-400">Whitelist: {ADMIN_EMAILS.join(', ')}</p></div></div>;
  }
  return <>{children}</>;
}

export function AdminPageShell({ title, description, children }: { title: string; description: string; children: React.ReactNode }) {
  return <AdminGuard><div className="min-h-screen bg-slate-100 px-4 py-8"><div className="mx-auto max-w-7xl space-y-5"><div className="rounded-3xl border border-orange-100 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><Link to="/admin" className="inline-flex items-center gap-2 text-sm font-black text-orange-600"><ArrowLeft size={16} /> Admin KaffePOS</Link><p className="mt-4 text-xs font-black uppercase tracking-[0.22em] text-orange-500">Internal Admin</p><h1 className="mt-2 text-2xl font-black text-slate-900 sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm font-medium text-slate-500">{description}</p></div><div className="flex flex-wrap gap-2"><Link className="rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-600" to="/admin/affiliates">Affiliates</Link><Link className="rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-600" to="/admin/referrals">Referrals</Link><Link className="rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-600" to="/admin/commissions">Commissions</Link></div></div></div>{children}</div></div></AdminGuard>;
}

export function LoadingCard() { return <div className="rounded-3xl border border-slate-100 bg-white p-10 text-center shadow-sm"><Loader2 className="mx-auto h-8 w-8 animate-spin text-[#FF6A00]" /><p className="mt-3 text-sm font-bold text-slate-500">Memuat data...</p></div>; }
export function ErrorCard({ message, onRetry }: { message: string; onRetry: () => void }) { return <div className="rounded-3xl border border-red-100 bg-white p-8 text-center shadow-sm"><p className="text-sm font-bold text-red-600">{message}</p><button onClick={onRetry} className="mt-4 inline-flex items-center gap-2 rounded-2xl bg-[#FF6A00] px-4 py-2 text-sm font-black text-white"><RefreshCw size={16} /> Coba Lagi</button></div>; }
export function EmptyState({ label }: { label: string }) { return <div className="px-5 py-12 text-center text-sm font-bold text-slate-500">{label}</div>; }
export function SummaryCards({ items }: { items: Array<{ label: string; value: string | number; money?: boolean }> }) { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{items.map((item) => <div key={item.label} className="rounded-3xl border border-slate-100 bg-white p-4 shadow-sm"><p className="text-xs font-black uppercase tracking-wide text-slate-400">{item.label}</p><p className="mt-2 text-2xl font-black text-slate-900">{item.money ? fRp(Number(item.value || 0)) : item.value}</p></div>)}</div>; }
export function StatusBadge({ status }: { status: string }) { const s=status?.toLowerCase(); const cls=s==='active'||s==='paid'||s==='rewarded'?'bg-emerald-50 text-emerald-700 border-emerald-100':s==='pending'||s==='eligible'||s==='registered'||s==='trial_started'||s==='approved'?'bg-orange-50 text-orange-700 border-orange-100':s==='rejected'||s==='cancelled'||s==='suspended'?'bg-rose-50 text-rose-700 border-rose-100':'bg-slate-50 text-slate-600 border-slate-100'; return <span className={`inline-flex rounded-full border px-3 py-1 text-xs font-black ${cls}`}>{status || '-'}</span>; }
export function Filters({ children, onRefresh }: { children: React.ReactNode; onRefresh: () => void }) { return <div className="rounded-3xl border border-slate-100 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center">{children}<button onClick={onRefresh} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-orange-100 bg-orange-50 px-4 py-3 text-sm font-black text-[#FF6A00]"><RefreshCw size={16} /> Refresh</button></div></div>; }
export function DetailModal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><div className="max-h-[88vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b border-slate-100 bg-white px-5 py-4"><h2 className="text-lg font-black text-slate-900">{title}</h2><button onClick={onClose} className="rounded-full bg-slate-100 p-2 text-slate-500"><X size={18} /></button></div><div className="p-5">{children}</div></div></div>; }
export function AdminInput(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 outline-none focus:border-orange-300 focus:ring-4 focus:ring-orange-50 lg:w-64" />; }
export function AdminSelect(props: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-black text-slate-700 outline-none focus:border-orange-300 focus:ring-4 focus:ring-orange-50" />; }
export function money(value: unknown) { return Number(value || 0); }
